### ISSUE TITLE
Add a getter for every with-Builder to allow to change values on a prodefined structure

### ISSUE THREAD

**Issue by aaschmid** [mkarneim/pojobuilder#108]
Hi @mkarneim,

I would like to provide a valid default builder structure with multiple levels for everybody. If you have to adjust a certain value with the structure, I would be nice to be able to access the deeper levels directly by using some getter for the nested builders.

But this would require to return the correct builder instead of `Builder<T>` which maybe hard to determine, wouldn't it?

Here is my example:

``` java
    public static GetAccountBuilder $validGetAccount() {
        return new GetAccountBuilder().withRequest(
                new GetAccountRequestBuilder()
                        .withClient(Client.ABC.clientId)
                        .withRequestTimestamp(toXmlGregorianCalendar(DateTime.now()))
                        .withUserID("1234567")
            );
    }
```

Now I would like to change the `userId` for another test case:

``` java
any($validGetAccount().getRequestBuilder().withUserID("987654")
```

Do you have any idea if this could be generated because otherwise I have to create a lot of builders myself.

Cheers,
Andreas

**Comment by aaschmid** [comment]
Maybe it is possible to add a new annotation to specify for which fields a builder should be generated and than also if getters should be generated for the builders. This would also make it possible to let you use the concrete classes instead of the builder inside of the relying builders. I think the generic case is not required here because why would you create multiple builders for the same pojo?

**Comment by mkarneim** [comment]
Hi Andreas!

This is an interesting question.

At my office we are thinking about this also.

I want to show you how we are doing it, although we are following a different approach.
We us a combination of  [Builder Factories](https://github.com/mkarneim/pojobuilder/wiki/Builder-Factory) and [Nested Builders](https://github.com/mkarneim/pojobuilder/wiki/Using-builders-within-builders), where we do not access builder members to redefine values, but we assign modified builders.

I try to make it clearer by using an example.

Let's start with creating an Order object using a [Builder Factory](https://github.com/mkarneim/pojobuilder/wiki/Builder-Factory).
```java
Order order = $Order().build();
```

Or, to make it more fluent:
```java
Order order = some($Order());
```

where ```some(...)``` is defined as:
```java
public static <P> P some(Builder<P> $builder) {
    return $builder.build();
}
```

The corresponding builder factory for the OrderBuilder looks like this:

```java
public static OrderBuilder $Order() {
    return new OrderBuilder()
      .withCustomer($Customer())
      .withOrderDate($Date());
}
```
As you can see, the OrderBuilder returned by the factory comes with two nested builders for the properties 'order.customer' and 'order.date'. Both are created by corresponding builder factories which look like this:

```java
public static CustomerBuilder $Customer() {
    return new CustomerBuilder()
      .withId($Long())
      .withName($String())
      .withAddress($Address());
}

public static DateBuilder $Date() {
    return new DateBuilder().withYear(2016).withMonth(1).withDay(1);
}
```
As you can see, this is a recursive pattern: again, the $Customer() method returns a CustomerBuilder with nested builders for 'customer.id', 'customer.name', and 'customer.address'.

For completeness, I show you the builder factory for Address:
```java
public static AddressBuilder $Address() {
    return new AddressBuilder()
      .withCity($String())
      .withPostCode($String())
      .withStreet($String());
}
```
The remaining builder factories ```$String()``` and ```$Long()``` are taken from the [TestDslBase](https://github.com/mkarneim/pojobuilder/blob/master/src/testdata/java/samples/dsl/TestDslBase.java).

Now, if you want to create an Order for some scenario where the customer must have some specific name, you can do it like this:
```java
Order order = some($Order()
      .withCustomer($Customer()
          .withName("Sherlock Holmes")));
```
As you can see, we do not modify the nested builder 'order.customer' directly, but we assign a new CustomerBuilder that has the required name.

This works also for nested-nested builders, as you can see in this example:
```java
Order order = some($Order()
      .withCustomer($Customer()
          .withName("Sherlock Holmes")
          .withAddress($Address()
            .withStreet("221b Baker Street")
            .withCity("London")
            .withPostCode("NW1 3RX")
)));
```

Please let me know if this would help you in your case.
If not, I might have some more examples about how we solve more complex use cases.

**Comment by aaschmid** [comment]
Hi @mkarneim, unfortunately this does not solve my problem. I really like your solution and it would solve my problems up to one point: 

Using your example I would like to put the 

```java
Order order = some($Order()
      .withCustomer($Customer()
          .withName("Sherlock Holmes")
          .withAddress($Address()
            .withStreet("221b Baker Street")
            .withCity("London")
            .withPostCode("NW1 3RX")
)));
```

into a method such that the developer can create the default hierarchy. As we have got really complex and big hierarchies which also differ per use case, I don't even want the developer to rebuild the complete hierarchy because of changing a field very deep within it, e.g. the developer wants to change the ```PostCode``` to ```""```to trigger a validation. Within a hierarchy containing up to 5 levels and up to 50 different builders, I don't want the developer to copy the calls to the correct sub builders over and over. Because of two reasons:
* the developer has to be aware to use the correct defaults depending on the use case
* as we are just setting up the project the defaults will change which forces the framework developer to catch every place where the wrong default builder is change ...
(on some places we have to have your above described approach also)

Do you understand my doubts?

If you cannot think about a generic solution or if you don't like it the way we currently use it, I will most likely go with the generation gap and create the getters myself. But this would also be an avoidable task ;-)

**Comment by mkarneim** [comment]
Alright, I already had the impression that your actual use case is more complex.

At our office we have this kind of use case when we want to create several scenarios for automated tests that have slightly varying test fixtures which we call *data setups*.

However, our solution to this is quite simple.
We use so called *setup builders* for creating specific data setups.

To do this, we are harnessing PojoBuilder's ability to create a builder by [annotating a factory method](https://github.com/mkarneim/pojobuilder#annotating-a-factory-method) and are using the fact that PB does not prevent you from creating more than one builder per pojo.

Here is an example. The following code generates a specialized setup builder called ```SherlockOrderBuilder ```, which can be used to create orders from Sherlock Holmes with varying post codes ;-).
```java
@GeneratePojoBuilder(
      withBuilderInterface = Builder.class, 
      withName = "SherlockOrderBuilder",
      excludeProperties = "*")
public static Order create(String addressPostCode) {
    String postCode = Optional.ofNullable(addressPostCode).orElse("NW1 3RX");
    return some($Order()
        .withCustomer($Customer()
            .withName("Sherlock Holmes")
            .withAddress($Address()
                .withStreet("221b Baker Street")
                .withCity("London")
                .withPostCode(postCode)))
    );
}
```
The generated builder can be used to create a pojo with a complex value setup where some of the values (here ```postCode```) can be configured by, I call them, *factory properties*, which are used as *setup options*.

A factory property is a property that can be set by calling a ```with```-method the same way as any other pojo property, but is not necessarily part of the pojo's declaration. It can be of any Java type and have any valid parameter name. PB generates a factory property for each parameter of the annotated factory method.

It's in the responsibility of the factory method how it handles the factory properties. In this case the ```addressPostCode``` parameter is passed down to the address part of the order's customer.

Please note, that I set the ```excludeProperties```directive to ```*```. While this is not necessary, I do recommend it, in order to prevent you from accidentally changing other values of the pojo. 

Now you can declare a builder factory for this new builder:
```java
public SherlockOrderBuilder $SherlockOrder() {
  return new SherlockOrderBuilder();
}
```
and use it in your code like this:
```java
Order order = some($SherlockOrder());
```

Or, fitting your example above, like this:
```java
Order order = some($SherlockOrder().withAddressPostCode(""));
```

Of course this is only a simple example. But I think you can get the idea.
In real life setup builders can become far more complex.
For example, we have a couple of setup builders that contain complex logic and loops. Some even declare one or more builders as setup options.

Please tell me if this could be solution for you.

PS:
Please let me add some final thoughts, in case you are using setup builders for automated tests.
Since test fixtures are mostly specific to certain test scenarios, I recommend that you declare setup builders in the same spot where you write the tests that are using them. This makes it easier for the reader to understand the tests and prevents you from reusing them all to excessively.

**Comment by aaschmid** [comment]
I think I get the idea but create so much code for a single or at most some few test cases seems a bit too much effort for me. This means I will start with the generation gap for at least some of my test cases. If this does not work I will think about another solution with your described approaches. Thank you for your comprehensive answers and the corresponding effort as well as for this great plugin :-)

**Comment by mkarneim** [comment]
@aaschmid can we assume this issue as resolved?

**Comment by aaschmid** [comment]
Hi @mkarneim, if you don't see it to introduce such a getter ... your can mark it as "won't fix" and close, yes :-)

**Comment by mkarneim** [comment]
Ah, I don't want to close this if this is still open for you.
If my suggestions do not work for you, we still can try to find a solution together.
If I understand you right, you have some work around using generation gap, haven't you?
Maybe you want to elaborate you solution with some complete examples?
And if you have an idea how PB could integrate that, please feel free to post some code that shows how the generated builder will look like, since I am still not sure how this could be done in PB.

**Comment by aaschmid** [comment]
Hi @mkarneim, as I cannot access the code where I used the pojobuilder and had the problem described above, here are the things out of my mind:

* I need to access ```RequestBuilder``` from the ```GetAccountBuilder``` builder as described in my first post
* I can create the ```RequestBuilder getRequestBuilder() { return builder$request$com$example$Request; }``` method myself within the ```GetAccountBuilder``` using ```@GeneratePojoBuilder(withGenerationGap = true)```
* I think the solution should be fairly easy by adding a property to ```@GeneratePojoBuilder```, e.g. ```@GeneratePojoBuilder(withGettersForBuilder = true)```

I also read the comments above and I think this solution would be much easier for me to 

* retrieve values from a builder hierarchy where I need the value ```builder.getBuilderA().getBuilderB().getValue()```
* I can avoid a lot of code if I just want to change some values within a huge "default hierarchy", e.g. ```builder.getBuilderA().getBuilderB().withValue("new1")```, ```builder.getBuilderC().getBuilderA().withValue("new2")```, ...

I like the idea to make things more explicit as you described it in your comments but I doubt others will use it properly if they cannot just use existing stuff and must create builder structures theirselves. This make the hurdles too high I assume ...

If I will find some time in the near future I will try to implement it ... keep your fingers crossed :-)
